language: "python"
python:
   - "2.7"
   - "pypy"
install:
  - pip install -r requirements.txt
  - pip install Django==$DJANGO_VERSION coveralls
env:
  - DJANGO_VERSION=1.5.8
  - DJANGO_VERSION=1.6.5
script:
   "coverage run runtests.py"
after_success:
   "coveralls"
