language: python

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"
  - "pypy3"

install:
  - pip install -r requirements.txt
  - pip install Django$DJANGO_VERSION coveralls

env:
  - DJANGO_VERSION=">=1.8.0,<1.9.0"
  - DJANGO_VERSION=">=1.9.0,<1.10.0"
  - DJANGO_VERSION=">=1.10.0,<1.11.0"
  - DJANGO_VERSION=">=2.0.0,<2.1.0"
  - DJANGO_VERSION=">=2.1.0,<2.2.0"

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO_VERSION=">=2.0.0,<2.1.0"
    - python: "2.7"
      env: DJANGO_VERSION=">=2.1.0,<2.2.0"
    - python: "3.8"
      env: DJANGO_VERSION=">=1.9.0,<1.10.0"
    - python: "pypy"
      env: DJANGO_VERSION=">=2.0.0,<2.1.0"
    - python: "pypy"
      env: DJANGO_VERSION=">=2.1.0,<2.2.0"
    - python: "pypy3"
      env: DJANGO_VERSION=">=1.8.0,<1.9.0"
    - python: "pypy3"
      env: DJANGO_VERSION=">=1.9.0,<1.10.0"
    - python: "pypy3"
      env: DJANGO_VERSION=">=1.10.0,<1.11.0"

script: "coverage run runtests.py"

after_success: "coveralls"
