version: 1
update_configs:
  # https://dependabot.com/docs/config-file/
  - package_manager: "python"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - "streeter"
    default_labels:
      - "dependencies"
